name: Fetch data

on:
  workflow_dispatch:

concurrency:
  group: option-chain-update
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Sync with latest remote
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Run bot
        run: |
          python main.py

      - name: Commit and push data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/nifty_option_chain.json

          git diff --staged --quiet && exit 0

          git commit -m "update option chain data"

          git push origin HEAD:main
