- name: Sync with latest remote
  run: |
    git fetch origin main
    git reset --hard origin/main

- name: Run bot
  run: python main.py

- name: Commit and push data
  run: |
    git config user.name "github-actions"
    git config user.email "actions@github.com"

    git add data/nifty_option_chain.json

    git diff --staged --quiet && exit 0

    git commit -m "update option chain data [skip ci]"
    git push origin HEAD:main
